site_name: Mercutio

repo_url: https://github.com/signebedi/mercutio

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - python

nav:
    - Getting Started: 'index.md'
    - Usage: 'usage.md'